### PR TITLE
Update waPlugin::buildFullTemplatePath()

### PR DESCRIPTION
**Pull request by WinterSilence**
Extends method comment and optimizes his code.

### CODE REVIEW

**Comment by mikeushenin** [comment]
Fixing what issue is your pull request aimed at?

**Comment by WinterSilence** [comment]
@mikeushenin optimization + normalization Windows paths

**Comment by mikeushenin** [comment]
> @mikeushenin optimization + normalization Windows paths

You have described the _purpose_ of your code changes but not the _issue_ which they are supposed to fix. Please _describe how to reproduce the issue_ that will occur with the use of the current code state, before your changes.

**Comment by WinterSilence** [comment]
`waPlugin::buildFullTemplatePath('actions', '\frontend\pluginAction.html');`

> You have described the purpose of your code changes but not the issue which they are supposed to fix.

PR does not necessarily fix some bug/issue, it's can be refactoring or new features.

**Pull request closed without merging**
